"use client"
import { motion } from "framer-motion"
import { Typography, Container, Paper, Box, Divider } from "@mui/material"
import { format } from "date-fns"

export default function TermsOfService() {
  const lastUpdated = "2023-04-15"

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <Container maxWidth="md">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <Paper elevation={2} className="p-8 rounded-lg">
            <Typography variant="h3" component="h1" className="text-3xl font-bold mb-2 text-center">
              Terms of Service
            </Typography>
            <Typography variant="body2" className="text-center text-gray-500 mb-6">
              Last Updated: {format(new Date(lastUpdated), "MMMM d, yyyy")}
            </Typography>

            <Divider className="mb-6" />

            <Box className="space-y-6">
              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  1. Introduction
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  Welcome to DisputeResolve ("Company", "we", "our", "us"). These Terms of Service ("Terms", "Terms of
                  Service") govern your use of our website and platform located at www.disputeresolve.com (together or
                  individually "Service") operated by DisputeResolve.
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and
                  disclose information that results from your use of our web pages. Please read it here.
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part
                  of the terms, then you may not access the Service.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  2. Definitions
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>SERVICE</strong> means the www.disputeresolve.com website and platform operated by
                  DisputeResolve.
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those
                  data (or from those and other information either in our possession or likely to come into our
                  possession).
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>USAGE DATA</strong> means data collected automatically either generated by the use of the
                  Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>COOKIES</strong> are small pieces of data stored on your device (computer or mobile device).
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>DATA CONTROLLER</strong> means the natural or legal person who (either alone or jointly or in
                  common with other persons) determines the purposes for which and the manner in which any personal
                  information are, or are to be, processed.
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  <strong>DATA SUBJECT</strong> is any living individual who is using our Service and is the subject of
                  Personal Data.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  3. Use of the Service
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  The Service is intended only for users who are at least 18 years of age. By using the Service, you
                  warrant that you are at least 18 years of age and you are able to form legally binding contracts. If
                  you are under 18 years of age, you may not use the Service.
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  You are responsible for maintaining the confidentiality of your account and password, including but
                  not limited to the restriction of access to your computer and/or account. You agree to accept
                  responsibility for any and all activities or actions that occur under your account and/or password.
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  You may not use the Service for any illegal or unauthorized purpose. You must not, in the use of the
                  Service, violate any laws in your jurisdiction (including but not limited to copyright laws).
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  4. Dispute Resolution Process
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  Our platform provides various methods of dispute resolution, including negotiation, mediation, and
                  arbitration. By using our Service, you agree to abide by the rules and procedures established for each
                  method.
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>Negotiation:</strong> The negotiation process is non-binding until both parties reach and sign
                  an agreement. You agree to negotiate in good faith and to provide accurate information throughout the
                  process.
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  <strong>Mediation:</strong> Mediation is a voluntary process facilitated by a neutral third party. The
                  mediator does not make decisions but helps parties reach their own agreement. Any agreement reached
                  through mediation becomes binding once signed by all parties.
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  <strong>Arbitration:</strong> By choosing arbitration, you agree that the arbitrator's decision will
                  be final and binding. You waive your right to pursue the dispute in court, subject to applicable laws.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  5. Fees and Payment
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  We charge fees for the use of our Service as outlined in our pricing information. Fees may vary based
                  on the type of dispute, resolution method chosen, and complexity of the case.
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  Payment must be made in advance for certain services. All fees are non-refundable unless otherwise
                  specified or required by law.
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  We reserve the right to change our fees at any time. Any changes will be posted on our website and
                  will not affect cases already in progress.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  6. Intellectual Property
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  The Service and its original content (excluding content provided by users), features, and
                  functionality are and will remain the exclusive property of DisputeResolve and its licensors. The
                  Service is protected by copyright, trademark, and other laws of both the United States and foreign
                  countries.
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  Our trademarks and trade dress may not be used in connection with any product or service without the
                  prior written consent of DisputeResolve.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  7. Limitation of Liability
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  In no event shall DisputeResolve, nor its directors, employees, partners, agents, suppliers, or
                  affiliates, be liable for any indirect, incidental, special, consequential or punitive damages,
                  including without limitation, loss of profits, data, use, goodwill, or other intangible losses,
                  resulting from:
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  (i) your access to or use of or inability to access or use the Service;
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  (ii) any conduct or content of any third party on the Service;
                </Typography>
                <Typography variant="body1" className="mb-3 text-gray-700">
                  (iii) any content obtained from the Service; and
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  (iv) unauthorized access, use or alteration of your transmissions or content, whether based on
                  warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been
                  informed of the possibility of such damage.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  8. Changes to Terms
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a
                  revision is material we will try to provide at least 30 days' notice prior to any new terms taking
                  effect. What constitutes a material change will be determined at our sole discretion.
                </Typography>
              </section>

              <section>
                <Typography variant="h5" component="h2" className="font-bold mb-3">
                  9. Contact Us
                </Typography>
                <Typography variant="body1" className="text-gray-700">
                  If you have any questions about these Terms, please contact us at legal@disputeresolve.com.
                </Typography>
              </section>
            </Box>
          </Paper>
        </motion.div>
      </Container>
    </div>
  )
}
